### ISSUE TITLE
프론트가 받을 이벤트

### ISSUE THREAD

**Issue by ghonman2** [pooh-transcendence/frontend#25]
# 이벤트 정리

```  JSON
{
  "event" : "addChannelToAllChannelList",
  "channel" : "channelId, ChannelName 등등 한꺼번에 날라감. "
}
```
- visiable channel List에 channel 추가해주시면 됩니다.
 
```  JSON
{
"event" : "addChannelToUserChannelList",
"data" : "channelId, channelName 등등  json 한꺼번에 날라감" 
}

```

- 사용자 Channel에 다가 channel 추가하시면 됩니다.

``` JSON
{
 "event" : "deleteChannelToAllChannelList",
  "data" : "channelId, ChannelName 등등  json 한꺼번에 날라감. "
}

```

- 사용자 channel에서 channel 삭제입니다.

``` JSON
{
 "event" : "addFriendToFriendList",
  "data"  : "userId 랑 nickname, avator가 날아감"
}

```
 - 사용자 Friend 에서 friend 추가할 때 습니다.

``` JSON
{
 "event" : "deleteFriendToFriendList",
  "data"  : "userId 랑 nickname, avator가 날아감"
}
```

- 이건 아시죠 ? 

block도 똑같은 맥락으로 갈 예정

**Comment by r4pidstart** [comment]
헬로 이제야 시간이 좀 나서 테스트하고 짜보고있어요

메인레포에 pr이 안 돼있길래 주원님 레포 최신버전 그대로 가져와서 테스트 좀 해봤어요.

한 가지 요청드리고싶은건, 보내주시는 정보들을 원래 친구/블럭 리스트 보낼때 형식 그대로 보내주실 수 있으신가요

addFriendToFriendList는 지금 id만 보내주는데, 전체 리스트를 다시 요청하던지, 해당 id에 대한 정보를 다시 요청해서 채워넣어야 하는 문제가 있거든요.

리스트에서 삭제될때는 단순히 id만 보내주셔도 필터가 가능한데, 추가하려면 더 정보가 필요해요.

요거랑,
deleteFriendToFriendList는 지금 유저 블럭시 친구목록에서 삭제되는걸로 알고있는데, 이 때 이벤트가 날아올거라 생각했으나 안 날아오더라구요? 

addChannelToUserChannelList는 있는데, 
deleteChannelToUserChannelList는 없어서 이거 만들어주셔야 할 것 같고,

addChannelToAllChannelList랑 deleteChannelToAllChannelList도 지금 제대로 작동 안 해요.

마지막으로 유저 상태가 온라인에서 오프라인으로 바뀐다던가, 하여튼 변경됐을때마다 변경된 유저 정보 보내주는 부분도 필요해요.
더 필요한거 있으면 나중에 말씀드릴게요.
