### ISSUE TITLE
프론트분들 해야할일 적어두고 갈게요

### ISSUE THREAD

**Issue by ghonman2** [pooh-transcendence/frontend#3]
디폴트 : 디자인 만들기 (끝 날때 까지 진행해주세요)

1. 로그인 구현하기 
   1) Oauth에서 로그인이 되면 accessToken을 백엔드에게 넘겨주세요. 
   2) backend는 accessToken을 주면 2차 인증(google auth)을 qr_code URL을 던져 드릴 겁니다. 
   이를 프론트 화면에 이 qr_code와 비밀 번호 입력 할 수 있는 창을 만들어 주세요.
   3) 그럼 2차 인증의 비밀번호를 넘겨주면 /Chat으로 나오게 해주세요 .

2. 로그인이 되면 backend에서 받은 토큰으로 socket.handshake.auth 에 토큰 넣는 거 만들어서 connection 맺게 해주세요

**Comment by kylew1004** [comment]
여윽시 Joowpark님
확실히 처리하겠습니다.
