### ISSUE TITLE
졌는데 이겼다고 나옵니다! 

### ISSUE THREAD

**Issue by ghonman2** [pooh-transcendence/frontend#70]
<img width="1027" alt="스크린샷 2023-09-05 오후 4 48 12" src="https://github.com/pooh-transcendence/frontend/assets/124144405/b18a1b86-a55d-4101-abb4-13695db2d09b">

**Comment by ghonman2** [comment]
정확히는 점수가 제대로 안나와요 ㅠ

**Comment by r4pidstart** [comment]
점수가 거꾸로 나오는거예요?
저거 아마 제가 좀 날림으로 해갖고 ㅋㅋㅋ 함 볼게요
