### ISSUE TITLE
invite에서 에러가 납니다

### ISSUE THREAD

**Issue by ghonman2** [pooh-transcendence/frontend#75]
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'includes')

Source
app/chat/ChatUserSearch.tsx (103:188) @ includes

  101 |         Object.entries(userList).map(
  102 |             ([idx, friend]) => {
> 103 |                 return <UserListComponent key={idx} userId={friend.id} nick={friend.nickname} profileImg={friend.avatar} type={state.channelChattingInfo.inviteSelectedList.includes(friend.id) ? "inviteFriend_1" : "inviteFriend_0"} />
      |                                                                                                                                                                            ^
  104 |             })
  105 |     }
  106 | </div>
Call Stack
map
app/chat/ChatUserSearch.tsx (101:49)
Show collapsed frames

<img width="940" alt="스크린샷 2023-09-06 오전 11 55 39" src="https://github.com/pooh-transcendence/frontend/assets/124144405/942265d1-6872-4ccc-9bef-3fd343a65e93">

**Comment by r4pidstart** [comment]
아마도 고쳐졌을텐데 문제 있으면 다시 말해주세요
